# Generated by Django 4.0.1 on 2022-02-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auto',
            new_name='author',
        ),
    ]
